name: Question
description: Ask a question about Monozukuri
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant context or what you've already tried
