#!/usr/bin/env bats
# test/unit/cmd_init_bootstrap.bats
# Unit tests for Phase B — foreign-project bootstrap (_init_bootstrap_context)

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../.." && pwd)"

# ── helpers ───────────────────────────────────────────────────────────────────

# Load only the two standalone functions without running sub_init.
# We source cmd/init.sh inside a sub-shell after stubbing out dependencies.
_load_init_fns() {
  # Minimal stubs so sourcing cmd/init.sh doesn't fail in test env.
  banner()  { :; }
  info()    { :; }
  err()     { :; }
  gum()     { :; }

  # Stub stack_profile_init: exports known test values.
  stack_profile_init() {
    export PROJECT_STACK="nodejs"
    export PROJECT_STACK_SUBTYPE="nextjs"
    export PROJECT_TEST_CMD="jest"
    export PROJECT_BUILD_CMD="npm run build"
    export PROJECT_PACKAGE_MANAGER="npm"
  }

  declare -f conventions_merge_write &>/dev/null || \
    source "$REPO_ROOT/lib/agent/conventions-merge.sh" 2>/dev/null || true

  # Provide LIB_DIR so the source guards inside _init_bootstrap_context work.
  export LIB_DIR="$REPO_ROOT/lib"

  # Inline both functions — the quickest way to load them without running sub_init.
  source /dev/stdin <<'SRC'
_init_write_context_file() {
  local path="$1" stack="$2" test_cmd="$3" build_cmd="$4"
  {
    printf '# Project Context\n\n'
    printf '<!-- Generated by monozukuri init — edit freely. -->\n\n'
    printf '## Stack\n\n'
    printf -- '- **Primary:** %s\n' "$stack"
    [ -n "$test_cmd"  ] && printf -- '- **Test:** `%s`\n' "$test_cmd"
    [ -n "$build_cmd" ] && printf -- '- **Build:** `%s`\n' "$build_cmd"
    printf '\n## Notes\n\nAdd project-specific conventions here.\n'
  } > "$path"
}

_init_bootstrap_context() {
  local agent="$1"
  local project_root="${PROJECT_ROOT:-.}"

  declare -f stack_profile_init &>/dev/null || \
    source "$LIB_DIR/core/stack-profile.sh" 2>/dev/null || true
  declare -f conventions_merge_write &>/dev/null || \
    source "$LIB_DIR/agent/conventions-merge.sh" 2>/dev/null || true

  stack_profile_init "$project_root" 2>/dev/null || true
  local stack="${PROJECT_STACK:-unknown}"
  local test_cmd="${PROJECT_TEST_CMD:-}"
  local build_cmd="${PROJECT_BUILD_CMD:-}"
  local pkg_mgr="${PROJECT_PACKAGE_MANAGER:-unknown}"

  local tmp_block; tmp_block=$(mktemp)
  {
    printf '%s\n' '<!-- monozukuri:generated-start v1 -->'
    printf '%s\n\n' '<!-- Generated by monozukuri init -->'
    printf '%s\n\n' '## Project Stack'
    printf -- '- **Stack:** %s\n' "$stack"
    [ "$pkg_mgr" != "unknown" ] && printf -- '- **Package manager:** %s\n' "$pkg_mgr"
    [ -n "$test_cmd"  ] && printf -- '- **Test:** `%s`\n' "$test_cmd"
    [ -n "$build_cmd" ] && printf -- '- **Build:** `%s`\n' "$build_cmd"
    printf '\n%s\n' '<!-- monozukuri:generated-end -->'
  } > "$tmp_block"

  if declare -f conventions_merge_write &>/dev/null; then
    conventions_merge_write "$project_root" "$tmp_block" 2>/dev/null || true
    info "Created/updated AGENTS.md (stack: $stack)"
  fi
  rm -f "$tmp_block"

  case "$agent" in
    claude-code)
      if [ ! -f "$project_root/CLAUDE.md" ]; then
        _init_write_context_file "$project_root/CLAUDE.md" "$stack" "$test_cmd" "$build_cmd"
        info "Created CLAUDE.md"
      fi
      ;;
    gemini)
      if [ ! -f "$project_root/GEMINI.md" ]; then
        _init_write_context_file "$project_root/GEMINI.md" "$stack" "$test_cmd" "$build_cmd"
        info "Created GEMINI.md"
      fi
      ;;
  esac
}
SRC
}

# ── B1: AGENTS.md creation ───────────────────────────────────────────────────

@test "B1: empty project → AGENTS.md created with stack profile" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "codex"
    [ -f "$tmp_dir/AGENTS.md" ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: AGENTS.md contains detected stack name" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "codex"
    grep -q "nodejs" "$tmp_dir/AGENTS.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: AGENTS.md contains monozukuri generated markers" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "codex"
    grep -q "monozukuri:generated-start" "$tmp_dir/AGENTS.md" && \
      grep -q "monozukuri:generated-end" "$tmp_dir/AGENTS.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: AGENTS.md contains test command" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "codex"
    grep -q "jest" "$tmp_dir/AGENTS.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: re-running bootstrap merges without duplicating markers" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "codex"
    _init_bootstrap_context "codex"
    local start_count; start_count=$(grep -c "monozukuri:generated-start" "$tmp_dir/AGENTS.md")
    [ "$start_count" -eq 1 ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: existing content above markers is preserved on re-run" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    # First run
    _init_bootstrap_context "codex"
    # Prepend user content above the generated block
    local agents_md="$tmp_dir/AGENTS.md"
    local tmp_prepend; tmp_prepend=$(mktemp)
    { printf '# My custom header\n\n'; cat "$agents_md"; } > "$tmp_prepend"
    mv "$tmp_prepend" "$agents_md"
    # Second run — must not destroy custom header
    _init_bootstrap_context "codex"
    grep -q "My custom header" "$tmp_dir/AGENTS.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

# ── B1: CLAUDE.md for claude-code agent ──────────────────────────────────────

@test "B1: agent=claude-code → CLAUDE.md created if missing" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "claude-code"
    [ -f "$tmp_dir/CLAUDE.md" ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: agent=claude-code → CLAUDE.md contains stack profile" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "claude-code"
    grep -q "nodejs" "$tmp_dir/CLAUDE.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: agent=claude-code → existing CLAUDE.md is not overwritten" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  echo "SENTINEL_CONTENT" > "$tmp_dir/CLAUDE.md"
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "claude-code"
    grep -q "SENTINEL_CONTENT" "$tmp_dir/CLAUDE.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: agent=claude-code → GEMINI.md is not created" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "claude-code"
    [ ! -f "$tmp_dir/GEMINI.md" ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

# ── B1: GEMINI.md for gemini agent ───────────────────────────────────────────

@test "B1: agent=gemini → GEMINI.md created if missing" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "gemini"
    [ -f "$tmp_dir/GEMINI.md" ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: agent=gemini → GEMINI.md contains stack profile" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "gemini"
    grep -q "nodejs" "$tmp_dir/GEMINI.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: agent=gemini → existing GEMINI.md is not overwritten" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  echo "SENTINEL_GEMINI" > "$tmp_dir/GEMINI.md"
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "gemini"
    grep -q "SENTINEL_GEMINI" "$tmp_dir/GEMINI.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

@test "B1: agent=gemini → CLAUDE.md is not created" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "gemini"
    [ ! -f "$tmp_dir/CLAUDE.md" ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

# ── B1: codex agent (no extra file) ──────────────────────────────────────────

@test "B1: agent=codex → no CLAUDE.md or GEMINI.md created" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    _init_bootstrap_context "codex"
    [ ! -f "$tmp_dir/CLAUDE.md" ] && [ ! -f "$tmp_dir/GEMINI.md" ]
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}

# ── B1: unknown stack fallback ────────────────────────────────────────────────

@test "B1: unknown stack → AGENTS.md still created with 'unknown'" {
  local tmp_dir; tmp_dir=$(mktemp -d)
  (
    export PROJECT_ROOT="$tmp_dir"
    _load_init_fns
    # Override stub after _load_init_fns to produce unknown stack
    stack_profile_init() {
      export PROJECT_STACK="unknown"
      export PROJECT_TEST_CMD=""
      export PROJECT_BUILD_CMD=""
      export PROJECT_PACKAGE_MANAGER="unknown"
    }
    _init_bootstrap_context "codex"
    [ -f "$tmp_dir/AGENTS.md" ] && grep -q "unknown" "$tmp_dir/AGENTS.md"
  )
  local rc=$?
  rm -rf "$tmp_dir"
  [ "$rc" -eq 0 ]
}
